### ISSUE TITLE
SAE needs to allow EMAPA IDs

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#37] opened 2018-03-12 15:35 UTC
Although the SAE allows me to autocomplete EMAPA IDs for mouse anatomy terms (as you can see in attached picture), it then shows them with an error, saying it is expecting an Uberon ID instead.

![20180310-ccextsbyautocomplete](https://user-images.githubusercontent.com/10533218/37293329-30f61232-25d0-11e8-9e3b-9f7aaacc1e3e.jpg)

Here's the model: http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5a98684700000052

**Comment by thomaspd** [comment] 2018-03-14 18:54
This looks like the same basic issue as #32 . @cmungall can you also address this one?  @tmushayahama, for both of these when you are reading the graph to populate the SAE form and check validity, you'll need to recognize additional prefixes (EMAPA and WBbt) as valid anatomy terms, just like UBERON.

**Comment by cmungall** [comment] 2018-03-14 20:35
These two are different. #32 is dependent on me merging in the uberon-to-wbbt bridge, which will done after validation.

We already have uberon-bridge-to-emapa.owl merged in, which means that mapped EMAPA classes will show up as subclasses of uberon anatomical entity. I confirmed this:

http://noctua-golr.berkeleybop.org/select?q=bronchus&defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&facet=true&facet.mincount=1&fq=document_category:%22ontology_class%22&fq=isa_closure:%22UBERON:0001062%22&qf=annotation_class%5E3&qf=annotation_class_label_searchable%5E5.5&qf=synonym_searchable%5E1&fl=id,annotation_class_label,idspace

you can see this includes EMAPA bronchus (as well as Uberon. We need curator guidelines as to what to pick when, especially as we increasingly annotate outside our species).

It looks like @tmushayahama is implementing an addition constraint such that the ID is expected to be in the Uberon ID space. I generally discourage making any assumptions about IDs, for ontologies, or databases. Use the ontology to discover semantics.

**Closed** 2018-04-03 03:54 UTC

**Comment by tmushayahama** [comment] 2018-04-03 03:57
can you double check on this one.

**Comment by krchristie** [comment] 2018-04-03 16:43
Well, it isn't throwing an error about an EMAPA term anymore, but this isn't working right either.

Here is what I entered:

![ccfullentryformw-emapa](https://user-images.githubusercontent.com/10533218/38262823-34ed7f4c-3723-11e8-9cbb-ef231a5e04c5.jpg)

Here is what it saved:

![savedfrom-ccfullentryformw-emapa](https://user-images.githubusercontent.com/10533218/38262854-3d0ad17a-3723-11e8-986e-919ca71df06f.jpg)

Note that the saved annoton failed to save the first CC term and then moved the cell type and anatomy terms up one blank in the annoton.

**Comment by krchristie** [comment] 2018-04-03 18:28
Also, while the autocomplete on an EMAPA term works **_IF_** the correct term shows up, I could not get the term I wanted to show up in the autocomplete list.

I wanted the term "**trachea**" (EMAPA:16853), but when I used "trachea " (note presence of space after word), I got this:
![trachea-autocomplete](https://user-images.githubusercontent.com/10533218/38268058-0b08418a-3732-11e8-8a82-f19485ba377c.jpg)


and when I used the ID, I got a larger selection of EMAPA choices, but NOT the one that matched the ID I put into the box:
![emapa-idautocomplete](https://user-images.githubusercontent.com/10533218/38268083-17014d38-3732-11e8-9bad-aae156988765.jpg)
