### ISSUE TITLE
Add clone evidence functionality

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#55] opened 2018-04-11 16:09 UTC
To make adding evidence easier and faster, we would like to have the ability to clone existing evidence from a model.

This functionality would be an option in the right hand list and would present curators with a list of existing evidence codes, references, and With/From values where curators could select what they want to clone and add to their model.

@tmushayahama  - see the 'Clone other' feature for adding evidence in the graphical interface for an example of how this was implemented.

**Comment by tmushayahama** [comment] 2018-04-13 17:40
To Clone

Click the more options and click clone evidence
![image](https://user-images.githubusercontent.com/2273929/38749392-4a854372-3f06-11e8-95ad-4bd618336928.png)

Select one or more evidence from the list. The recent evidence appears on top and there will be no duplicate of (evidence, reference and with) combination on the list
![image](https://user-images.githubusercontent.com/2273929/38749487-9e7da0dc-3f06-11e8-94d0-3151b1df2f3b.png)

Note: 'with' and 'assignedBy' doesn't get copied

**Closed by tmushayahama** 2018-04-13 17:40 UTC
